channels:
  - defaults
dependencies:
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.2
  - python=3.7.11
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.2
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - anyio==3.5.0
    - appdirs==1.4.4
    - appnope==0.1.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==21.4.0
    - autograd==1.3
    - babel==2.9.1
    - backcall==0.2.0
    - backports-csv==1.0.7
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - blis==0.7.6
    - bs4==0.0.1
    - cachetools==5.0.0
    - catalogue==2.0.6
    - cffi==1.15.0
    - chardet==3.0.4
    - charset-normalizer==2.0.12
    - cheroot==8.6.0
    - cherrypy==18.6.1
    - click==8.0.4
    - cryptography==36.0.1
    - cssselect==1.1.0
    - cycler==0.11.0
    - cymem==2.0.6
    - cytoolz==0.11.2
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.4
    - docx==0.2.4
    - ecommercetools==0.42.3
    - entrypoints==0.4
    - fake-useragent==0.1.11
    - feedparser==6.0.8
    - filelock==3.6.0
    - fonttools==4.30.0
    - future==0.18.2
    - gapandas==1.0
    - google-api-core==2.7.1
    - google-api-python-client==2.39.0
    - google-auth==2.6.0
    - google-auth-httplib2==0.1.0
    - googleapis-common-protos==1.55.0
    - httplib2==0.20.4
    - huggingface-hub==0.4.0
    - idna==2.10
    - importlib-metadata==4.11.2
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - ipykernel==6.9.1
    - ipython==7.32.0
    - ipython-genutils==0.2.0
    - jaraco-classes==3.2.1
    - jaraco-collections==3.5.1
    - jaraco-context==4.1.1
    - jaraco-functools==3.5.0
    - jaraco-text==3.7.0
    - jedi==0.18.1
    - jellyfish==0.9.0
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyter-server==1.13.5
    - jupyterlab==3.3.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - kiwisolver==1.3.2
    - langcodes==3.3.0
    - lifetimes==0.11.3
    - lxml==4.8.0
    - markupsafe==2.1.0
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - more-itertools==8.12.0
    - murmurhash==1.0.6
    - nbclassic==0.3.6
    - nbclient==0.5.12
    - nbconvert==6.4.2
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - nltk==3.7
    - notebook==6.4.8
    - notebook-shim==0.1.0
    - numpy==1.21.5
    - oauth2client==4.1.3
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parse==1.19.0
    - parso==0.8.3
    - pathy==0.6.1
    - patsy==0.5.2
    - pattern3==3.0.0
    - pdfminer-six==20211012
    - pdfminer3k==1.3.4
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - pluggy==1.0.0
    - ply==3.11
    - portend==3.1.0
    - preshed==3.0.6
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - protobuf==3.19.4
    - ptyprocess==0.7.0
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycausalimpact==0.1.1
    - pycparser==2.21
    - pydantic==1.8.2
    - pyee==8.2.2
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyphen==0.12.0
    - pyppeteer==1.0.2
    - pyquery==1.4.3
    - pyrsistent==0.18.1
    - pytest==7.1.1
    - python-dateutil==2.8.2
    - python-docx==0.8.11
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.3.0
    - regex==2022.3.2
    - requests==2.23.0
    - requests-html==0.10.0
    - rsa==4.8
    - sacremoses==0.0.47
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - segtok==1.5.11
    - send2trash==1.8.0
    - sgmllib3k==1.0.0
    - simplejson==3.17.6
    - six==1.16.0
    - sklearn==0.0
    - smart-open==5.2.1
    - sniffio==1.2.0
    - soupsieve==2.3.1
    - spacy==3.2.3
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - statsmodels==0.13.2
    - tabulate==0.8.9
    - tempora==5.0.1
    - terminado==0.13.3
    - testpath==0.6.0
    - textacy==0.11.0
    - thinc==8.0.13
    - threadpoolctl==3.1.0
    - tokenizers==0.11.6
    - tomli==2.0.1
    - toolz==0.11.2
    - torch==1.10.2
    - tornado==6.1
    - tqdm==4.63.0
    - traitlets==5.1.1
    - transformers==4.17.0
    - typer==0.4.0
    - typing-extensions==3.10.0.2
    - uritemplate==4.1.1
    - urllib3==1.25.11
    - w3lib==1.22.0
    - wasabi==0.9.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.1
    - websockets==10.2
    - wikipedia==1.4.0
    - yake==0.4.8
    - zc-lockfile==2.0
    - zipp==3.7.0
